<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Create</title>
    <link rel="stylesheet" href = "../css/style.css">
    <script src="../js/script.js"></script>
  </head>
  <body>
    <textarea id="code_snippet" class="code_snippet" name="create"></textarea>
    <button id="send_snippet" class="send_snippet" type="submit" onclick="send()">Submit</button>
  </body>
</html>