<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Create</title>
        <link rel="stylesheet" href = "../css/style.css">
        <script src="../js/script.js"></script>
        <link rel="stylesheet"
               target="_blank" target="_blank" target="_blank" target="_blank" target="_blank" href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/styles/default.min.css">
        <script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/highlight.min.js"></script>
        <script>hljs.initHighlightingOnLoad();</script>
    </head>
    <body>
        <textarea id="code_snippet" class="code_snippet" name="create"></textarea>
        <button id="send_snippet" class="send_snippet" type="submit" onclick="send()">Submit</button>
    </body>
</html>